Repository Nerdy-In-Room/QUIZ_BACKEND_SERVER, pull requests merged in 2025-02, with the labels that each got.

#75 접속한 서버에 따른 웹소켓 연결 문제
  build.gradle
  src/main/java/com/example/quiz/config/cacheConfig/CaffeineCacheConfig.java
  src/main/java/com/example/quiz/config/cacheConfig/redis/RedisConfig.java
  src/main/java/com/example/quiz/config/cacheConfig/redis/RedisEventPublisher.java
  src/main/java/com/example/quiz/config/cacheConfig/redis/RedisEventSubscriber.java
  src/main/java/com/example/quiz/config/stompConfig/StompConfig.java
  src/main/java/com/example/quiz/config/stompConfig/StompEventListener.java
  src/main/java/com/example/quiz/dto/room/ChangeCurrentOccupancies.java
  src/main/java/com/example/quiz/entity/Game.java
  src/main/java/com/example/quiz/service/RoomProducerService.java
  src/main/java/com/example/quiz/service/RoomService.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
  src/main/resources/static/script/room.js
Labels: 🐞 BugFix

#78 STOMP 인터셉트 추가
  src/main/java/com/example/quiz/config/stompConfig/StompChannelInterceptor.java
Labels: 🔨 Refactor

#80 인게임 웹소켓 연결 불가
  src/main/java/com/example/quiz/config/cacheConfig/redis/RedisConfig.java
  src/main/java/com/example/quiz/config/cacheConfig/redis/RedisEventPublisher.java
  src/main/java/com/example/quiz/config/cacheConfig/redis/RedisEventSubscriber.java
  src/main/java/com/example/quiz/config/stompConfig/StompConfig.java
  src/main/java/com/example/quiz/config/stompConfig/StompEventListener.java
  src/main/java/com/example/quiz/controller/RoomController.java
  src/main/java/com/example/quiz/dto/room/response/RoomResponse.java
  src/main/java/com/example/quiz/service/RoomService.java
  src/main/resources/static/script/game.js
  src/main/resources/static/script/quiz.js
Labels: 🐞 BugFix

#83 Bug/남은퀴즈갱신2
  src/main/java/com/example/quiz/config/stompConfig/StompChannelInterceptor.java
  src/main/java/com/example/quiz/dto/request/RequestAnswer.java
  src/main/java/com/example/quiz/dto/response/ResponseQuiz.java
  src/main/java/com/example/quiz/service/GameService.java
  src/main/java/com/example/quiz/service/RoomService.java
  src/main/resources/static/script/game.js
  src/main/resources/static/script/quiz.js
  src/main/resources/templates/room.html
Labels: 🐞 BugFix

#84 OAuth2 라이브러리를 이용한 구현
  build.gradle
  src/main/java/com/example/quiz/config/SecurityConfig.java
  src/main/java/com/example/quiz/config/auth/CookieUtils.java
  src/main/java/com/example/quiz/config/auth/CustomDetailsService.java
  src/main/java/com/example/quiz/config/auth/CustomUserDetails.java
  src/main/java/com/example/quiz/config/auth/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/example/quiz/config/stompConfig/StompEventListener.java
  src/main/java/com/example/quiz/controller/UserController.java
  src/main/java/com/example/quiz/dto/User/LoginUserRequest.java
  src/main/java/com/example/quiz/entity/user/CustomAuthenticationSuccessHandler.java
  src/main/java/com/example/quiz/entity/user/CustomOAuth2User.java
  src/main/java/com/example/quiz/entity/user/User.java
  src/main/java/com/example/quiz/jwt/JWTRequestFilter.java
  src/main/java/com/example/quiz/jwt/JwtUtil.java
  src/main/java/com/example/quiz/mapper/RoomMapper.java
  src/main/java/com/example/quiz/repository/UserRepository.java
  src/main/java/com/example/quiz/service/CustomOAuth2UserService.java
  src/main/java/com/example/quiz/service/GameService.java
  src/main/java/com/example/quiz/service/RoomProducerService.java
  src/main/java/com/example/quiz/service/RoomService.java
  src/main/java/com/example/quiz/service/UserService.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/templates/index.html
Labels: 🔨 Refactor

#86 방 브로드캐스팅 안됨
  src/main/java/com/example/quiz/config/SecurityConfig.java
  src/main/java/com/example/quiz/config/auth/CookieUtils.java
  src/main/java/com/example/quiz/config/auth/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/example/quiz/service/RoomService.java
Labels: 🐞 BugFix

#88 room list에 같은 방이 여러번 나타나는 현상
  src/main/java/com/example/quiz/config/SecurityConfig.java
  src/main/java/com/example/quiz/config/auth/CookieUtils.java
  src/main/java/com/example/quiz/config/cacheConfig/redis/RedisConfig.java
  src/main/java/com/example/quiz/config/stompConfig/CustomHandshakeInterceptor.java
  src/main/java/com/example/quiz/config/stompConfig/StompChannelInterceptor.java
  src/main/java/com/example/quiz/config/stompConfig/StompConfig.java
  src/main/java/com/example/quiz/config/stompConfig/StompEventListener.java
  src/main/java/com/example/quiz/controller/RoomController.java
  src/main/java/com/example/quiz/service/RoomProducerService.java
  src/main/java/com/example/quiz/service/RoomService.java
  src/main/resources/static/script/game.js
  src/main/resources/static/script/index.js
  src/main/resources/static/script/room.js
  src/main/resources/templates/index.html
  src/main/resources/templates/quiz.html
  src/main/resources/templates/room.html
Labels: 🐞 BugFix

#90 모니터링을 위한 프로메테우스 추가
  src/main/java/com/example/quiz/config/SecurityConfig.java
  src/main/java/com/example/quiz/config/stompConfig/StompConfig.java
  src/main/java/com/example/quiz/service/RoomService.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
Labels: ✨ Feature

#92 프로메테우스 매트릭 추가
  src/main/java/com/example/quiz/jwt/JWTRequestFilter.java
  src/main/java/com/example/quiz/jwt/JwtUtil.java
  src/main/resources/application-prod.yaml
Labels: 🔨 Refactor
