Repository Nerdy-In-Room/QUIZ_BACKEND_SERVER, pull requests merged in 2025-01, with the labels that each got.

#52 방 생성 및 입장 로직 개선
  build.gradle
  src/main/java/com/example/quiz/config/BeanConfiguration.java
  src/main/java/com/example/quiz/config/stompConfig/JwtHandshakeInterceptor.java
  src/main/java/com/example/quiz/config/stompConfig/StompChannelInterceptor.java
  src/main/java/com/example/quiz/config/stompConfig/StompConfig.java
  src/main/java/com/example/quiz/config/stompConfig/StompEventListener.java
  src/main/java/com/example/quiz/repository/RoomRepository.java
  src/main/java/com/example/quiz/service/RoomProducerService.java
  src/main/java/com/example/quiz/service/RoomService.java
  src/main/java/com/example/quiz/service/UserService.java
  src/main/java/com/example/quiz/vo/InGameUser.java
  src/main/resources/static/script/room.js
  src/main/resources/templates/index.html
  src/test/java/com/example/quiz/service/RoomServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#54 STOMP 브로드캐스팅 최적화
  src/main/java/com/example/quiz/config/stompConfig/StompEventListener.java
  src/main/java/com/example/quiz/exception/RoomServiceExceptionHandler.java
  src/main/java/com/example/quiz/exception/WebSocketEventExceptionHandler.java
  src/main/java/com/example/quiz/repository/QuizRepository.java
  src/main/resources/static/script/room.js
  src/test/java/com/example/quiz/config/stompConfig/StompEventListenerTest.java
Labels: ✨ Feature

#57 기타 버그 수정
  src/main/java/com/example/quiz/controller/RoomController.java
  src/main/resources/templates/room.html
Labels: 🐞 BugFix

#63 변경 인원 최신 데이터만 유지
  src/main/java/com/example/quiz/config/stompConfig/StompEventListener.java
  src/main/java/com/example/quiz/controller/GameController.java
  src/main/java/com/example/quiz/controller/RoomController.java
  src/main/java/com/example/quiz/dto/room/ChangeCurrentOccupancies.java
  src/main/java/com/example/quiz/entity/Game.java
  src/main/java/com/example/quiz/service/RoomService.java
  src/main/resources/static/script/game.js
  src/main/resources/static/script/room.js
Labels: 🔨 Refactor

#69 게임 시작 시 대기방 삭제되는 현상
  src/main/resources/static/script/game.js
Labels: 🐞 BugFix

#70 남은 퀴즈 갱신 및 버그 수정
  src/main/java/com/example/quiz/controller/GameController.java
  src/main/java/com/example/quiz/controller/QuizController.java
  src/main/java/com/example/quiz/dto/request/RequestRemainQuiz.java
  src/main/java/com/example/quiz/dto/response/ResponseMessage.java
  src/main/java/com/example/quiz/dto/response/ResponseReadyGame.java
  src/main/java/com/example/quiz/dto/response/ResponseStartGame.java
  src/main/java/com/example/quiz/service/GameService.java
  src/main/resources/static/css/game.css
  src/main/resources/static/script/game.js
  src/main/resources/static/script/quiz.js
  src/main/resources/templates/quiz.html
  src/main/resources/templates/room.html
Labels: 🐞 BugFix

#71 방 생성 여러번 누르면 여러개의 방이 생성
  build.gradle
  src/main/java/com/example/quiz/config/cacheConfig/CacheConfig.java
  src/main/java/com/example/quiz/controller/GameController.java
  src/main/java/com/example/quiz/controller/RoomController.java
  src/main/java/com/example/quiz/dto/room/request/RoomCreateRequest.java
  src/main/java/com/example/quiz/entity/Room.java
  src/main/java/com/example/quiz/service/RoomProducerService.java
  src/main/java/com/example/quiz/service/RoomService.java
  src/main/resources/static/script/room.js
  src/main/resources/templates/index.html
Labels: 🐞 BugFix

#73 미사용 의존성 제거
  build.gradle
  gradlew
  src/main/java/com/example/quiz/config/RedisConfig.java
  src/main/java/com/example/quiz/controller/UserController.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
Labels: 🔨 Refactor
